config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home"
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password_confirmation, :password

  email_regex = /[\w+\-.]+@[a-zA-Z\d.\-]+\.[a-zA-Z]+/i

  validates :name, :presence => true,
                   :length => {:maximum => 50}

  validates :email, :presence => true,
                    :format => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false}

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40 }

  before_save :encrypt_password

  def User.authenticate(email, submitted_password)
    user = User.find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def User.authenticate_with_salt(id, cookie_salt)
    user = User.find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end


  def has_password?(submitted_password)
        encrypted_password == encrypt(submitted_password)
  end

  private

      def encrypt_password
        self.salt = make_salt if new_record?
        self.encrypted_password = encrypt(self.password)
      end

      def encrypt(string)
        secure_hash("#{salt}--#{string}")
      end

      def secure_hash(string)
        Digest::SHA2.hexdigest(string)
      end

      def make_salt
        secure_hash("#{Time.now.utc}--#{:password}")
      end

end





# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])

    if(user.nil?)
      @title = "Sign in"
      flash.now[:error] = "Wrong email/password"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"
  end

  def show
   @user = User.find(params[:id])
   @title = @user.name
  end

  def create

    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome to the sample app!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Ruby on Rails Tutorial Smaple App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("rails.png", :alt => "Sample App", :class => "round")
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {:size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.name, :gravatar => options , :class => "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <%= link_to "About", about_path %>
      <%= link_to "Contact", contact_path %>
      <%= link_to "Facebook", "http://www.facebook.com",  %>
      <%= link_to "Twitter", "http://www.twitter.com", :target => "alt" %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	      <%= link_to logo, root_path %>
	      <nav>
	        <ul>
	          <li><%= link_to "Home", root_path %></li>
	          <li><% if signed_in? %>
	          <%= link_to "Profile", user_path(current_user) %>
	          </li> <% end  %>
	          <li><%= link_to "Help", help_path %></li>
	          <% if signed_in? %>
	          <li><%= link_to "Sign out", signout_path %></li>
	          <% else %>
	          <li><%= link_to "Sign in", signin_path %></li>
	          <% end %>
	        </ul>
	      </nav>
 </header>

app/views/layouts/_stylesheet.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheet' %>
	</head>
	<body>
	  <div class="container">
	    <%= render 'layouts/header' %>

	    <section class="round">
	      <% flash.each do |key, value| %>
	        <div class="<%= key %>"><%= value %></div>
	      <% end %>
        <%= yield %>
	    </section>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
	  </div>

	</body>
</html>

app/views/pages/about.html.erb
		<h1>About Page</h1>
		<p>This is the About page <a href="./about">About</a></p>

app/views/pages/contact.html.erb
		<h1>Contact Page</h1>
		<p>This is the contact page <a href="./contact">contact</a></p>

app/views/pages/help.html.erb
		<h1>Help Page</h1>
		<p>This is the Help page <a href="./help">help</a></p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>This is the hole page <a href="./home">home</a></p>
<%= link_to "Sign Up Now!", signup_path , :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?  %>
  <div class="error">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>
    <p>There were problem with the following fields: </p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
  </div>
<% end  %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>

  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= f.label :name %> <br />
    <%= f.text_field :name %><br />

    <%= f.label :email %> <br />
    <%= f.email_field :email %> <br />

    <%= f.label :password %> <br />
    <%= f.password_field :password %> <br />

    <%= f.label :password_confirmation, "Confirm" %> <br />
    <%= f.password_field :password_confirmation %> <br />
  </div>

  <div class="action">
    <%= f.submit "Create Account" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user.id), @user %>
    </td>
  </tr>
</table>